name: Airtable

on:
  push:
    branches:
      - main
  schedule:
    # Hourly
    - cron: 0 * * * *

env:
  FORCE_COLOR: 1

jobs:
  airtable:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Download Earthly
        run: |
          sudo wget https://github.com/earthly/earthly/releases/download/v0.5.18/earthly-linux-amd64 -O /usr/local/bin/earthly
          sudo chmod +x /usr/local/bin/earthly

      - name: Install dependencies and build
        run: |
          earthly +docker

      - name: Update Airtable
        run: |
          docker run --rm \
            -e AIRTABLE_API_KEY="${{ secrets.AIRTABLE_API_KEY }}" \
            philly-311-airtable-bridge:latest
